language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - LARAVEL_VERSION=5.7
  - LARAVEL_VERSION=5.8
  - LARAVEL_VERSION=6.0
  - LARAVEL_VERSION=6.2

matrix:
  exclude:
    - php: 7.1
      env: LARAVEL_VERSION=6.0
    - php: 7.1
      env: LARAVEL_VERSION=6.2

before_install:
  - composer self-update >/dev/null 2>&1
  - composer require laravel/framework:${LARAVEL_VERSION} --no-update

install: composer update --prefer-source --no-interaction

script: vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    - hello@hisorange.me
# Thanks for this awesome service @TravisCI!
