name: Test php8

on: push

jobs:
  matrix-build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [8.0]
        # these versions supports php8 in their composer.json
        laravel-version: [6.19, 6.20, 7.29, 7.30.1, 8.4, 8.5]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}

      - name: Composer update
        run: composer self-update >/dev/null 2>&1

      - name: Laravel install
        env:
          LARAVEL_VERSION: ${{ matrix.laravel-version }}
        run: composer require laravel/framework:${{ matrix.laravel-version }} --no-update

      - name: Vendor update
        run: composer update --prefer-source --no-interaction

      - name: Run test suite
        run: composer run-script test
      # - name: Analyze/phpcs/Coveralls
      #   run: |
      #     "if [ $LARAVEL_VERSION = '8.0' ]; then vendor/bin/phpstan analyse -c phpstan.neon ./src/; fi"
      #     "if [ $LARAVEL_VERSION = '8.0' ]; then php vendor/bin/phpcs --standard=PSR12 ./src/; fi"
      #     "if [ $LARAVEL_VERSION = '8.0' ]; then php vendor/bin/coveralls -v; fi"
